packages:
  - 'frontend'
  - 'backend'
allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - '@prisma/client-runtime-utils@7.10.0'
  - '@prisma/client@7.10.0'
  - '@prisma/config@7.10.0'
  - '@prisma/debug@7.10.0'
  - '@prisma/engines@7.10.0'
  - '@prisma/fetch-engine@7.10.0'
  - '@prisma/get-platform@7.10.0'
  - prisma@7.10.0
